[profile.default]
gas_reports=[]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./" }]
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
evm_version = "prague" # for testing bls precompiles
seed = "0x1337"
solc = "0.8.29"
# via_ir = true

[fmt]
line_length = 120
int_types = "long"
tab_width = 4
quote_style = "double"
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  # OpenZeppelin contracts
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  
  # EigenLayer contracts
  "@eigenlayer/=lib/eigenlayer-contracts/src/contracts/",
  "@eigenlayer-middleware/=lib/eigenlayer-middleware/src/",
  
  # Other remappings
  "@karak/=lib/karak/",
  
  # Make sure these are available for existing imports
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
  "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

[rpc_endpoints]
mainnet ="https://green-cold-field.quiknode.pro/6cf9c5dcc0f6f4ce2aac712a6c0db86b035a22e4"
holesky ="https://green-cold-field.ethereum-holesky.quiknode.pro/6cf9c5dcc0f6f4ce2aac712a6c0db86b035a22e4"